language: node_js
node_js:
- node
before_script:
- npm install
notifications:
  email:
  - thomas.maclean@gmail.com
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "test.schaakbord"
  skip_cleanup: true
